'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, ChevronDown, Compass, Package, Search, ShoppingBag, Truck, Upload, X, Minus, Plus, RotateCcw } from 'lucide-react';

const products = [
  { name:'Zipper Hoodie', fabric:'320 GSM', prices:[600,550,525,500], colors:['Black','Charcoal','Grey'], image:'/products/zipper-hoodie.webp', category:'HOODIES' },
  { name:'Regular Hoodie', fabric:'320 GSM', prices:[550,525,500,475], colors:['Black','White','Green'], image:'/products/regular-hoodie.webp', category:'HOODIES' },
  { name:'Normal Polo', fabric:'180 GSM', prices:[450,400,380,350], colors:['Black','Navy','Maroon','Yellow','White','Grey'], image:'/products/normal-polo.webp', category:'T-SHIRTS' },
  { name:'Premium Polo', fabric:'220 GSM', prices:[475,450,410,380], colors:['Black','Navy','Red','White','Sky Blue'], image:'/products/premium-polo.webp', category:'T-SHIRTS' },
  { name:'Crew Neck T-Shirt', fabric:'180 GSM', prices:[450,400,380,350], colors:['Black','Navy','Maroon','Yellow','White','Grey'], image:'/products/crew-neck.webp', category:'T-SHIRTS' },
  { name:'Cap', fabric:'FREE SIZE', prices:[250,230,210,190], colors:['White','Black'], image:'/products/cap.webp', category:'ACCESSORIES' }
] as const;
const tiers=['UP TO 10','UP TO 20','UP TO 50','50+'];
type Product = typeof products[number];
const swatches:Record<string,string>={Black:'#151719',Charcoal:'#41464c',Grey:'#92979c',White:'#f7f7f4',Green:'#226d58',Navy:'#18265d',Maroon:'#8f243e',Yellow:'#e7d93c',Red:'#b52235','Sky Blue':'#7fb9d5'};

function Photo({product,art}:{product:Product;art?:string}) {
  return <div className="photoStage"><img className="catalogPhoto" src={product.image} alt={product.name} /><div className="artOverlay">{art&&<img src={art} alt="Your uploaded print" />}</div></div>;
}
function SceneGarment({product,art}:{product:Product;art?:string}) {
  return <div className="sceneGarment"><Photo product={product} art={art}/></div>;
}

export default function Home(){
  const [q,setQ]=useState(''),[selected,setSelected]=useState<Product|null>(null),[qty,setQty]=useState(10),[cart,setCart]=useState<{product:Product;qty:number;color:string;size:string;art:string}[]>([]),[cartOpen,setCartOpen]=useState(false),[color,setColor]=useState('Black'),[size,setSize]=useState('M'),[art,setArt]=useState(''),[activeRoom,setActiveRoom]=useState('All'),[tracking,setTracking]=useState(''),[tracked,setTracked]=useState(false),[showStore,setShowStore]=useState(false),[roomTurn,setRoomTurn]=useState(0);
  const list=useMemo(()=>products.filter(p=>(p.name.toLowerCase().includes(q.toLowerCase()))&&(activeRoom==='All'||p.category===activeRoom)),[q,activeRoom]);
  const tier=qty<=10?0:qty<=20?1:qty<=50?2:3;
  const cartCount=cart.reduce((n,x)=>n+x.qty,0),total=cart.reduce((n,x)=>n+x.product.prices[Math.min(x.qty<=10?0:x.qty<=20?1:x.qty<=50?2:3,3)]*x.qty,0);
  function customize(p:Product){setSelected(p);setQty(10);setColor(p.colors[0]);setSize(p.name==='Cap'?'Free size':'M');setArt('');setShowStore(false)}
  function upload(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>setArt(String(reader.result||''));reader.readAsDataURL(file)}
  function addToCart(){if(!selected)return;setCart(old=>[...old,{product:selected,qty,color,size,art}]);setSelected(null);setCartOpen(true)}
  return <main className="siteShell">
    <header className="topbar"><a className="brand" href="#"><span className="brandMark">PS</span><span>PrintStuff<small>MAKE IT YOURS</small></span></a><nav><a href="#showroom">Showroom</a><a href="#catalog">Shop products</a><a href="#process">How it works</a></nav><div className="topActions"><button className="textButton" onClick={()=>setShowStore(v=>!v)}>{showStore?'Explore showroom':'Shop all'}</button><button className="cartButton" onClick={()=>setCartOpen(true)} aria-label="Open cart"><ShoppingBag size={18}/><b>{cartCount}</b></button></div></header>
    <section id="showroom" className="showroomHero">
      <div className="heroCopy"><div className="eyebrow"><span className="liveDot"/> YOUR BRAND. YOUR MERCH.</div><h1>Walk in.<br/><em>Make it yours.</em></h1><p>Explore the PrintStuff virtual showroom, choose your favourite pieces and preview your artwork before you order.</p><div className="heroActions"><button className="primaryButton" onClick={()=>{setShowStore(true);document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'})}}>Explore products <ArrowRight size={17}/></button><button className="secondaryButton" onClick={()=>setRoomTurn(v=>v+1)}><RotateCcw size={16}/> Rotate view</button></div><div className="heroFacts"><span><b>06</b> product lines</span><span><b>Bulk</b> pricing</span><span><b>Custom</b> artwork</span></div></div>
      <div className={'virtualRoom turn'+(roomTurn%2)} aria-label="Interactive 3D showroom">
        <div className="roomGlow"/><div className="backWall"><div className="wallSign"><small>WELCOME TO</small><strong>PRINTSTUFF</strong><span>YOUR IDEAS, PRINTED.</span></div><div className="wallShelf shelfOne"><i/><i/><i/></div><div className="wallShelf shelfTwo"><i/><i/></div></div><div className="sideWall"/><div className="floorGrid"/>
        <button className="roomHotspot hotspotHoodie" onClick={()=>customize(products[0])}><span>01</span><b>HOODIES</b><small>Explore collection ↗</small></button><button className="roomHotspot hotspotTee" onClick={()=>customize(products[4])}><span>02</span><b>ESSENTIAL TEES</b><small>Customise yours ↗</small></button><button className="roomHotspot hotspotCap" onClick={()=>customize(products[5])}><span>03</span><b>ACCESSORIES</b><small>Shop caps ↗</small></button>
        <div className="displayTable"><div className="tableTop"><span>PRINT BAR</span><b>DESIGN / PRINT / WEAR</b></div><div className="tableLeg legA"/><div className="tableLeg legB"/><div className="miniProduct miniOne"><img src="/products/crew-neck.webp" alt="Crew neck T-shirt"/></div><div className="miniProduct miniTwo"><img src="/products/normal-polo.webp" alt="Polo T-shirt"/></div></div>
        <div className="roomControls"><span><Compass size={14}/> INTERACTIVE SHOWROOM</span><button onClick={()=>setRoomTurn(v=>v+1)} aria-label="Rotate showroom"><RotateCcw size={15}/></button></div>
      </div>
    </section>
    <div className="ticker"><span>BUILT FOR YOUR BRAND</span><i>✳</i><span>SMALL RUNS TO BULK ORDERS</span><i>✳</i><span>PRINT YOUR WAY</span><i>✳</i><span>BUILT FOR YOUR BRAND</span></div>
    <section id="catalog" className="catalogSection"><div className="sectionIntro"><div><div className="eyebrow">THE PRODUCT FLOOR</div><h2>Find your <em>blank canvas.</em></h2><p>Choose a product to customise with your artwork. Bulk prices update with quantity.</p></div><div className="searchBox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the collection"/></div></div>
      <div className="filterBar"><div className="filterTabs">{['All','HOODIES','T-SHIRTS','ACCESSORIES'].map(x=><button className={activeRoom===x?'active':''} key={x} onClick={()=>setActiveRoom(x)}>{x}</button>)}</div><span>{list.length} PRODUCTS <ChevronDown size={14}/></span></div>
      <div className="productGrid">{list.map((p,i)=><article className="productCard" key={p.name}><div className="productImageWrap"><span className="productIndex">0{products.indexOf(p)+1} / 06</span><Photo product={p}/><button className="quickAdd" onClick={()=>customize(p)}>CUSTOMISE <ArrowRight size={15}/></button></div><div className="productMeta"><div><span className="fabric">{p.fabric} · {p.category}</span><h3>{p.name}</h3></div><strong>₹{p.prices[3]}<small> / piece</small></strong></div><div className="productBottom"><div className="swatchLine">{p.colors.slice(0,5).map(c=><i key={c} title={c} style={{background:swatches[c]}}/>)}<span>{p.colors.length} colours</span></div><button onClick={()=>customize(p)}>View product ↗</button></div></article>)}</div>
    </section>
    <section className="bulkSection"><div><div className="eyebrow">MADE FOR TEAMS & BRANDS</div><h2>More pieces.<br/><em>Better prices.</em></h2><p>Transparent tiered pricing across the collection. Shipping is extra on all orders.</p></div><div className="bulkTable"><div className="bulkHead"><span>PRODUCT</span>{tiers.map(t=><span key={t}>{t}</span>)}</div>{products.map(p=><div className="bulkRow" key={p.name}><b>{p.name}</b>{p.prices.map((v,i)=><span key={i}>₹{v}</span>)}</div>)}</div></section>
    <section id="process" className="processSection"><div className="eyebrow">FROM IDEA TO DELIVERY</div><h2>Your design, <em>in motion.</em></h2><div className="processGrid"><div><span>01</span><Upload/><b>Upload your artwork</b><p>Bring your logo, illustration or print file.</p></div><div><span>02</span><Package/><b>Build your order</b><p>Choose colour, size and quantity.</p></div><div><span>03</span><CheckCircle2/><b>Production begins</b><p>Artwork review, printing and quality check.</p></div><div><span>04</span><Truck/><b>Delivered to you</b><p>Follow your order through each stage.</p></div></div></section>
    <section id="track" className="trackSection"><div><div className="eyebrow">ORDER STATUS</div><h2>From our floor<br/>to <em>your door.</em></h2><p>Enter an order number to check progress.</p></div><div className="trackPanel"><label>ORDER NUMBER</label><div className="trackInput"><input value={tracking} onChange={e=>{setTracking(e.target.value);setTracked(false)}} placeholder="e.g. PS-1001"/><button onClick={()=>setTracked(true)}>Track order <ArrowRight size={15}/></button></div>{tracked&&<div className="trackResult"><CheckCircle2/><div><b>{tracking||'PS-1001'}</b><span>Demo status: Printing · Quality check follows</span></div></div>}</div></section>
    <footer><a className="brand" href="#"><span className="brandMark">PS</span><span>PrintStuff<small>MAKE IT YOURS</small></span></a><span>Custom merchandise, made for your brand.</span><a href="/admin">Admin portal ↗</a></footer>
    {selected&&<div className="modalLayer"><button className="modalShade" onClick={()=>setSelected(null)} aria-label="Close customiser"/><aside className="customDrawer"><button className="closeButton" onClick={()=>setSelected(null)}><X/></button><div className="eyebrow">MAKE IT YOURS</div><h2>{selected.name}</h2><span className="fabric">{selected.fabric} · {selected.category}</span><div className="customPhoto"><Photo product={selected} art={art}/></div><label className="fieldLabel">COLOUR <b>{color}</b></label><div className="colorOptions">{selected.colors.map(c=><button key={c} title={c} aria-label={c} className={color===c?'chosen':''} style={{background:swatches[c]}} onClick={()=>setColor(c)}/>)}</div>{selected.name!=='Cap'&&<><label className="fieldLabel">SIZE</label><div className="sizeOptions">{['S','M','L','XL','XXL'].map(s=><button className={size===s?'chosenSize':''} key={s} onClick={()=>setSize(s)}>{s}</button>)}</div></>}<label className="fieldLabel">QUANTITY</label><div className="qtyControl"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={15}/></button><b>{qty}</b><button onClick={()=>setQty(qty+1)}><Plus size={15}/></button><span>{tiers[tier]} tier</span></div><label className="uploadControl"><Upload size={18}/><span><b>{art?'Artwork added':'Upload artwork'}</b><small>PNG, JPG, WEBP or SVG</small></span><input type="file" accept=".png,.jpg,.jpeg,.webp,.svg,image/*" onChange={e=>upload(e.target.files?.[0])}/></label>{art&&<button className="removeArtwork" onClick={()=>setArt('')}>Remove uploaded artwork</button>}<div className="drawerTotal"><span>₹{selected.prices[tier]} / piece<small>Shipping extra</small></span><b>₹{(selected.prices[tier]*qty).toLocaleString('en-IN')}</b></div><button className="primaryButton fullButton" onClick={addToCart}>Add to cart <ShoppingBag size={17}/></button></aside></div>}
    {cartOpen&&<div className="modalLayer cartLayer"><button className="modalShade" onClick={()=>setCartOpen(false)} aria-label="Close cart"/><aside className="customDrawer cartDrawer"><button className="closeButton" onClick={()=>setCartOpen(false)}><X/></button><div className="eyebrow">YOUR SELECTION</div><h2>Shopping cart <span className="cartCount">{cartCount}</span></h2>{cart.length===0?<div className="emptyCart"><ShoppingBag size={40}/><h3>Your cart is waiting.</h3><p>Explore the showroom and add your first custom piece.</p><button className="primaryButton fullButton" onClick={()=>{setCartOpen(false);document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'})}}>Explore products <ArrowRight size={16}/></button></div>:<><div className="cartItems">{cart.map((item,i)=><div className="cartItem" key={i}><img src={item.product.image} alt={item.product.name}/><div><b>{item.product.name}</b><span>{item.color} · {item.size} · Qty {item.qty}</span><strong>₹{(item.product.prices[Math.min(item.qty<=10?0:item.qty<=20?1:item.qty<=50?2:3,3)]*item.qty).toLocaleString('en-IN')}</strong></div><button aria-label="Remove item" onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><X size={16}/></button></div>)}</div><div className="drawerTotal"><span>Subtotal<small>Shipping calculated separately</small></span><b>₹{total.toLocaleString('en-IN')}</b></div><button className="primaryButton fullButton" onClick={()=>{const text=cart.map(x=>x.product.name+' | '+x.color+' | '+x.size+' | Qty '+x.qty).join('\n');window.location.href='mailto:orders@printstuff.in?subject='+encodeURIComponent('PrintStuff custom order enquiry')+'&body='+encodeURIComponent(text+'\nEstimated subtotal: ₹'+total)}}>Request order quote <ArrowRight size={17}/></button><p className="checkoutNote">This sends an order enquiry by email; online payment can be connected when checkout details are configured.</p></>}</aside></div>}
  </main>
}
